# Base image
FROM afdaniele/ros-system-monitor-standalone:latest

# copy launch script
COPY assets/system_monitor.launch /system_monitor.launch

# copy config file
COPY assets/system_monitor_config.yaml /system_monitor_config.yaml
